language: java
jdk: oraclejdk8
dist: trusty
cache:
  directories:
  - $HOME/.m2
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install: cd singa-all
script: travis_wait mvn --settings .travis/settings.xml clean verify
deploy:
  -
    provider: script
    script: travis_wait .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: cleberecht/singa
      jdk: oraclejdk8