language: java
jdk: jdk11
dist: bionic
sudo: required
addons:
  apt:
    packages:
      - oracle-java8-installer
      - r-base

env:
  global:
    - secure: "oKBf6W2GxUfCe80287zcVkjuGZuA3DntBG6hGm6BG/pM72Sc8u244g4aezHjRj6R2aZr6wmbY7+p9cXClz05KElrLRsFcwfl2zz5RbcKupY/o9GqotUu4tZkrQIZ3ltFHhLmDm9qMJ/W/3C4sbrakwOmA2wRbYEw5QNBmvAfRI4dqYTL6pg1VF1m4xeP5PZkqPCNAURN+leUcXSNlhcnpo8z4TOG+mgr9UL70hIPXXCPqRmZ+DDNiSOouyvaHGiK0VcWJlgdyd6WsIZiSYQptRpGJ7vTLMw4/WAIsj/CzMZ//+H99JcQhvXY562yxU8uqYDxQ5twmRq2Os8g/lxHsWm0JD+p1m7uN5uvb/Qi7gXAgJKgRgzVA39sqAEiUzAcZCXnTPRKN+6j5ZIqgVW/ErRWWoWsevlEcHAVN+QiKm4aKapFQKmiE6j9f+DKA74tE/l8MjIUmecm36vPdMFwQ0eIlUNbDFngCbcKtOJdgIY9t1sfV/8O0WRodDdlXkXlHscE+/ESawInYaghDThiCal+b7iikflaSbsyLaVr39HWec80sCDxwsFWaJFrtBxUaB6YlU5hi0vywM5Kop59l1P5RtvQ5mi0tsJpZCWFYkSg2GbZS0+g0aAiwepC8Zp2JCNcoNAQeoukgwR0KKWqcZV+R3KdIAw78hzwm/wqNIc="
    - # ^^ OSSRH_JIRA_USERNAME
    - secure: "bcHSrMakp4bfU6jhHM66n/Bf+ypMir/P40K2czEjWb2pVHGRxvXoOQqaFtxZVm2EaKWcFzsSR6vwbwmAf9cGy559MgLhpgB0YbUMMFVVfxR3D1NtXoP9tqlhhG+7HAe6j6Z/1Sb8c1nm8mDl8s4wPaIOQjRBcoIRoqtLlWIvEP8siNsO//tBxOlrA+6jYIFKkkJwCnXAyT1Kqp/foW6TO+qfVQaMOD3L7r+5I0T7832EDOLOjtApmiNT3LzJ3whItUSqdnYWSYUromuXeXb62GAxm0NRpk9kAPPQnex5bfFLBY+jNBgU3tykF5OG1i7LPt28IyNmCe56mWgG/uRxJrbXJB2DXD+an7ywaL48/icYFWlfRA7LY6Bd53eukV8QjIqJ+iWIk9c09uxtxUbSGjdSVEdarOu39EoC2exhUAT2LiabrtsjsUZnLAAzr3wLQ9ac117nmzntCZyZEUjvG5IM7y771N67JC7YUFZw2GdnzASOGuu3+tTu3xx29kcQHu+55e+8pZk2VJhubUqplny7+Xtt0yJz8OEWr3G+UqHZ5MVKloT3DW0A3q5d60nvjDupRaqRaSEizMm5XYD56+nMGSpfTwpecwFQIU8BvatbZbwu+6P/PSQAwVSDCduhpYRzvjadfuAT1F72+2Ok+STKaqoCwx4evmE6i4dPfv0="
    - # ^^ OSSRH_JIRA_PASSWORD
    - secure: "V2G8W67YQlnJwPuZTHDUUxd3QQjtt75YaCFKVntAwlHNVCdBNVARMrkzTKT+GpSUWxcCMLrJ+hBSwOUZGRV310L68roF3Lpak7vcF1qwDJcqVytwnyd7RCk9NHMBuqI/LNof5TeCfXZFHTCQiEaVxX8Yx4r+OB70VHp+UGiKIQWvWl7XDPz9uHYpXxXqdpnJEZSx/E33ZMOGh72IkGeymtum4glnmTMguc+UofRCMjzSbCiWPFfSqj9egM0lHFl0oeuE3+I6dKXfcjLYnKwqUebRW/rKc7E0sFQp5KaaMrRnFeckNLJqeGculxJBT2xpqvwNbkIhIXytGn9VcgrjtutT2PpuAxCiqeY9rq0V6SeW/9DWUlYe3VWquyG1YO5JbaH4LN87Q6wqKyRUXW3NTk3dz+wuweucOol6Wu4zQZzRxAcs0SfDNTxkbKcRHbno+O81YHFlHHCQlqomuiiIO0IR5HzdpNYeIA0JoNayzIwP4YLhNIi+uTlJLohNwkDvOAMprHSU/F20OGvnStr0qcrJJczPjwwRnXErR6Q8m+Ezo2EilYxTwYj+cxy5QJEWESlxXnpuwk9AgZfi/0rkypDSmdHWmrJtmHhnqDrg4BgnEwqa8J7b0zc1XYJflgGZSjiNqbxFxXOvwuSu+TpCrSQRjaBfMhvO8PGtc8emSjg="
    - # ^^ GPG_KEY_NAME
    - secure: "k8l/0HmlN0khdoW/NRrM23kX2Y7TqcNwTP5WpqA0MnlClsQMa4BBp7zDijaOZdUsLsH2crhc387pzN2vP9JZOjYI7o47oyfI1eMLPHopM8fbg+m8mnA4I494P25y6kFQennL6jp0gpKtuhIZqx4+hB4D/DHxaFaPKckkCkSkQGoj/RGa1TlSUpIZuss4kpT7OOnUIHoQ4DCvtJX4yoHkx6YQYETEdeVXHuGuEwBhXgHoCATG8s7sYZ6TS+VYZ2kyuW5m9nOWmkjYElRWYOaVka5tcnmdT0BU5+MFAN2PPBJjD+SPZMF2ElAUhejqKwPr6OIhjxHx9llCN3jHV0ctU0aRBMKdWEbBEfshhUolrlfVC8qh+Jx/RwbctCuxtYnUdtak6ecDEHfSHu8vDPh0nBeM+bT0fmqE7FWZB+8TC7KrCrQYwaac6nazcS6Ag8sBH4rmKRJSE5OV+5EUcySnlzVsRwpscH2WLZe77I1B6elyEVKn8tndfH9AiBseeWCkGh0v681jD6ARcbBl76DZ0yMIoy8mdVZzRaYsq4uvYH9PWiK95i9vzJyXtGQvTuYIgTHX4gXXQHOY5ppiJ5JRYq3xWKBeRpobMSY4p07EJD6WUY+tg6IEcWp+tHiyrwaYsz1dnq9lW7Bzhe6s768kG6Ibpm0Gy6RuVVJAuFO4d2s="
    - # ^^ GPG_PASSPHRASE
    - secure: "hGo6DfgIuhOyFi6iuv6aA5sOVsQXFQmE7t3eDCn93xc6ic8icxGeixx+v/+PWVcTUjgSlX5bYOwsNrc+vsnz/qi4t1LEsQTdM0f3+6luwhnUel/O89Qk4GV3SA7TW5i4edhSw5EYYchybjfBhQ3BFJkBFxLvqEBN9GL/mkUW/6pCfa/mUBvjK3QjbAju6iydKX7bXiK/Yt1Dfpu4XoufkTf7MlWeQB5rkNZQzm1xaa7zP2iMlvc5sR8UY2qkXhhWqScfAZkKEyc297FP9yuqudNbkn8f9ilZfpBwFlEw0R+MGF2hTdqnx+OiHYmiHNB56AnMY5d0pM5ZmFy8AEjFmWFrS0KO6GkpskuhMgalCt2HCpOV3+13d7NPqEb3NHGvv4EZTc8aYGfeGdTWSTKfmK1FjryP+ytT57wMROVJgmLRh6mTC8v9hQ46GVz6pj9wty+zol9Ul6JXAykoEHSo95YUkhplSHKf7TaqwEgTJcAXblb71ZQ1NnrSc8Iqmndyq4t9NnWRrbRvim86CDFnqOsTN4oWbwtaplbBqxqWw/HQ66c4Q/SkFSvmzphlW+5MN6eQbGijHNmMUD0OS1TN1BFLNT7ntaHxCJw+H6UPIiM6MsE6hWaTYlRwpZfYHsEcCxzkCCfJfMVbOZZ+Tx2poQ5P2BpszOZo98jfE2n5M0Q="
    - # ^^ GITHUB_DOC_TOKEN

before_install:
  - cd singa-all

install:
  - sudo apt-get install r-base
  - sudo Rscript -e 'install.packages("sfsmisc", repos="https://cran.rstudio.com/", lib="/usr/lib/R/library")'
  - mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: mvn test -P !build-extras -B

after_success:
  - ./cd/before-deploy.sh
  - ./cd/deploy.sh
  - ./cd/publish-documentation.sh

cache:
  directories:
    - ~/.m2/repository